== 基本的な使用方法

=== 導入

下記のコマンドを入力して、本環境のローカルコピーを取得し、取得したディレクトリに移動してください。

[source,shell]
----
git clone https://github.com/develhack/jpdoc.git # 本環境のローカルコピーを取得
cd jpdoc # 本環境のローカルコピーに移動
----

[IMPORTANT]
====
以降の説明は全て、本環境のローカルコピーがカレントディレクトリである事が前提です。
====

本環境の構成は以下となっています。

----
jpdoc/
│  build.gradle <1>
│  :
│
├─fonts/ <2>
├─themes/ <3>
├─templates/ <4>
└─manual/ <5>
    │  build.gradle <6>
    │
    └─src/docs/asciidoc/ <7>
                 │  manual.adoc <8>
                 │
                 ├─_includes/ <9>
                 └─_diagrams/ <10>
----

<1> 本環境を使用するためのビルドスクリプトです。全てのサブプロジェクトに対する設定を行います。
<2> 日本語を出力するためのフォントが格納されています。
<3> PDFに適用するテーマが格納されています。
<4> PDFに合成するテンプレートが格納されています。
<5> このドキュメントを作成するためのサブプロジェクトです。本環境の使用例として参照してください。
<6> サブプロジェクト固有の設定を行うビルドスクリプトです。
<7> PDFのソースファイルを配置するディレクトリです。
<8> このドキュメントのソースファイルです。
<9> ドキュメントの断片となる（``manual.adoc``に埋め込まれる）ソースファイルが格納されています。
<10> ドキュメントに埋め込まれる図形のソースファイルが格納されています。

[NOTE]
====
``_``（アンダーバー）で始まるディレクトリ配下のソースファイルはコンパイル対象から除外される設定になっています。
====

<<<

=== ドキュメントの作成

ドキュメントを作成する際には、作成するドキュメント用のサブプロジェクトを作成します。

``__<サブプロジェクト>__/src/docs/asciidoc``ディレクトリ配下に作成した、拡張子が``.adoc``のファイルがPDFのソースファイルとして認識されます。

[[settings]]
=== ドキュメントの設定

``__<サブプロジェクト>__/build.gradle``を作成する事で、そのサブプロジェクトにより出力されるPDFの設定を変更する事が出来ます。設定可能な項目は以下の3つです。

.サブプロジェクトの設定項目
[cols="5,4,24a", options="header"]
|===
^|設定項目 ^|規定値 ^|説明

|theme | ``'default'`` |
ドキュメントに適用するテーマを指定します。 +
テーマの使用方法は「<<theme>>」を参照してください。

|template | ``''``
|
ドキュメントに適用するPDFテンプレートもしくは動的テンプレートを指定します。下記の``templateValues``の指定有無によって、PDFテンプレートを使用するか動的テンプレートを使用するかが決まります。
PDFテンプレートの使用方法は「<<template>>」を、動的テンプレートの使用方法は「<<dynamic-template>>」をそれぞれ参照してください。

|templateValues | ``[]``
|
動的テンプレートに適用する置換文字列を指定します。 +
動的テンプレートの使用方法は「<<dynamic-template>>」を参照してください。

|===

このドキュメントの設定は下記の通りです。

[source,groovy]
----
include::{build-gradle}[]
----

=== PDFの出力

下記コマンドを実行するとPDFが出力されます。

[source,shell]
----
./gradlew asciidoctor # 全てのサブプロジェクトのPDFを出力
./gradlew example:asciidoctor # exampleサブプロジェクトのPDFを出力
----

PDFは ``__<サブプロジェクト>__/build/asciidoc/pdf`` ディレクトリ配下に出力されます。

PDFテンプレート機能および動的テンプレート機能を使用する場合は、テンプレートと合成されたPDFが ``__<サブプロジェクト>__/build/asciidoc/pdf/finalized`` ディレクトリ配下に出力されます。